### PR TITLE
[moved to gitlab] port to the meson build system

### PR DESCRIPTION
**Pull request by eli-schwartz**
The meson build system is a fast, modern, ergonomic build system with great support for python extensions and cython.

### CODE REVIEW

**Comment by mbridon** [comment]
Hi Eli, thank you very much for that!! 😁 

I'm at my parents for the week, I'll try it out as soon as possible though 😄

Out of curiosity, I know Meson is pretty well documented, so I guess everything you used can be understood from the docs? I don't remember out quickly Meson moves or deprecates old things, should we be good to go with this for sometime, or do you expect some things to stop working soon?

**Comment by eli-schwartz** [comment]
> I'm at my parents for the week, I'll try it out as soon as possible though :smile:

Have a wonderful time and don't interrupt that on my account then. :smile:

> I don't remember out quickly Meson moves or deprecates old things, should we be good to go with this for sometime, or do you expect some things to stop working soon?

Meson only deprecates old things if it's decided that that way of doing it was somehow a mistake, but if that does happen then meson will continue to work with old build files, and simply issue a deprecation warning.

I would say we take deprecations pretty seriously now that meson is semver 1.x -- with some reluctance, I've made even meson.build files that intentionally violate type safety keep working and just emit a "this was always broken and is now deprecated" warning. The plan is to drop support for *that* for 2.0.

General deprecations for features that were once considered good style but are now considered undesirable may also be dropped at a semver major bump (again, after first issuing deprecation warnings), but we'll also want to make sure that it's been long enough since it was deprecated that no one is still stuck using old meson versions that don't support the new way, e.g. there are no oldstale versions of Ubuntu that are still in LTS support but ship a stone-age meson that cannot handle the new functionality.

...

All that being said, I don't have an expectation that anything I used here will ever go out of style. In fact, I went and required a fairly modern version of meson so that I can use some neat modern approaches to the python module (extensions automatically handling the python dependency for you, setting `pure: false` at find_installation time).

**Comment by mbridon** [comment]
Alright, you convinced me 🤤 

As soon as I can I'll test this and report back, probably merging the pull request.

A bit of background though, how involved are you with Meson or Python development? Just to know if I can ask you for some more help in the future 😆

**Comment by eli-schwartz** [comment]
I'm a core developer for meson with over 800 commits, so quite well indeed. ;)

Feel free to ask me anything about it, I give you full permission to `@mention` me on your own bug tracker(s) if you'd like insight into meson.

I'm not actively involved in python core development, but meson is one of the modern, decently popular build backends in the python *packaging* community, and a hefty part of my work on meson has related to integrating meson as a python packaging build backend. I'm guessing you're more interested in "python (packaging) development" than "python (core) development"?

**Comment by mbridon** [comment]
Yeah, you guessed right 😉

If that's the case, I'm still interested in a port to Meson for the libcangjie and ibus-cangjie build systems 😁

**Comment by eli-schwartz** [comment]
This PR has migrated over to https://gitlab.freedesktop.org/cangjie/pycangjie/-/merge_requests/43

**Pull request closed without merging**
