### PR TITLE
Docker based testing

### PR DESCRIPTION
**Pull request by yookoala**
1. Added Dockerfile to build docker image with pycangjie available as a system package.
  This enable docker based testing of ibus-cangjie.

2. Disables local Travis build to circumvent #30.

3. Added Docker based test in Travis.

### CODE REVIEW

**Comment by bochecha** [comment]
So let me get this straight.

1. you created the Cangjians/build-essential repo with a Dockerfile
2. you made the Cangjians/libcangjie CI build in Docker with its own Dockerfile based on the Cangjians/build-essential one
3. you made the Cangjians/pycangjie CI build in Docker with its own Dockerfile based on the Cangjians/libcangjie one

And this way, we move beyond the old Ubuntu builders: you used Ubuntu 16.04 in the Cangjians/build-essential Dockerfile, but I assume we could use anything else, right?

That's an nice approach!

However I've been wondering about something a bit different for some time... Gitlab CI would allow us to better control on which platform(s) we build, and it's generally much more powerful than Travis. See https://github.com/Cangjians/ibus-cangjie/issues/80 for the discussion about that.

**Comment by yookoala** [comment]
You basically get it.

Docker provides multiple base images of different system. Besides Ubuntu, we can have build-eseential image based on [Fedora][fedora], [Arch Linux][archlinux].

[fedora]: https://hub.docker.com/_/fedora/
[archlinux]: https://hub.docker.com/r/base/archlinux/ 

Advantage of this approach:
1. Running docker on any Linux distro is easy. With multiple build-essential images, we can all do multiple OS testing on our own workstation without worrying about VM installation.
2. That means we can change a line of code and test on multiple OS with our own workstation. No need to push.
3. We can also manually override local builds if we are developing multiple layer in the stack (e.g. some experiment on libcangjie, pycangjie, ibus-cangjie all together).
4. We actually get to test the compilation instructions on different OS every time we run tests.

**Comment by yookoala** [comment]
Reading the Gitlab approach, will comment on [Cangjians/ibus-cangjie#80](Cangjians/ibus-cangjie#80).

**Comment by yookoala** [comment]
Improved the current approach to support multiple OS test.

How does it work in testing environment:

1. Each test setup defines a `$OS` variable in the environment. (i.e. "ubuntu-16.04" and "fedora-25")
2. When the tests start, travis pull the [build-essential](https://hub.docker.com/r/cangjians/build-essential/) image of the given os tag defined in Travis. Then re-tag it as "build-essential:latest" locally.
3. Build the other images on it one by one.
4. Run test on the top-most image.

**Pull request closed without merging**
